### ISSUE TITLE
Documentation site Link not working

### ISSUE THREAD

**Issue by ansarizafar** [devsu/condor-framework#28]
Documentation link is not working. Framework looks great. Are you using it in production? Is there any road map available?

**Comment by jdgutierrez** [comment]
Hi @ansarizafar, right now we're under a major change on our framework and the docs will be affected by this, we should be publishing the changes this week, included the new docs. Sorry for the inconvenience.

Regards

**Comment by jdgutierrez** [comment]
Hi @ansarizafar, we finished publishing the new changes to the framework and the documentation, it take us longer than we expected, sorry to keep you waiting, you can check the docs [here](http://condorjs.com/).

Regards
