### ISSUE TITLE
Just wanted to drop a line.

### ISSUE THREAD

**Issue by thedodd** [devsu/condor-framework#31]
Just wanted to drop a line and say hello. This project is awesome. Exactly what I was looking for. Let me know if there is anything I can help out with. Going to be using this pretty heavily.

**Comment by c3s4r** [comment]
Hi. Thanks for writing! 👍  ... right now I think the best way to help is to start using it and providing feedback. Contributing with middleware modules would also be great. (We're working on a few, but are focused only on our current needs for our projects...) As soon as we have a few more, I'd like to add a new page in the documentation with the list of middleware modules, so people can start using them as well. Any PR is welcome! :)
