### ISSUE TITLE
A test harness would be awesome.

### ISSUE THREAD

**Issue by thedodd** [devsu/condor-framework#32]
I have been using this system a decent bit now, and the only thing which appears to be missing (or perhaps it is simply undocumented) is a testing harness. Testing the services is simple enough, but I need to be able to test the service in combination with middleware and the other inner workings of the node grpc lib (type checking &c).

Any thoughts on next steps?

**Comment by c3s4r** [comment]
Hi. Probably we can have a little more documentation on this, but this is how I would approach testing:

For **unit** tests: you don't need any dependency. They should be simple, and just test that the middleware for example do what it should do depending on the parameters that it receives.
For **integration** tests, this is what I would do:

- In a ´beforeAll´ method, I would start the server and a grpc client, (along with any other dependencies I have).

```js
beforeAll(() => {
    initializeCondorServer();
    initializeCondorClient();
  });

function initializeCondorServer() {
    condor = new Condor()
      .addService(protoPath, 'samplePackage.SamplesService', new Service())
      .start();
  }

  function initializeCondorClient() {
    const coreProto = grpc.load(protoPath);
    client = new coreProto.samplePackage
      .SamplesService('127.0.0.1:3000', grpc.credentials.createInsecure());
  }
```

You would also need the code to stop your server after running your tests:

```js
 afterAll((done) => {
   condor.stop().then(done)
 });
```

Then, on your tests, you can use your client to execute the actions, and verify that the response is correct.

You can take a look at the tests on this library for an idea on how we're doing integration tests: (it's a work in progress, so don't expect it to be perfect)... https://github.com/devsu/condor-mongoose/blob/master/lib/crud-base-service.integration.spec.js

If you have any ideas on other utils that we might need to make testing easier, let me know!

**Comment by thedodd** [comment]
Awesome. That should definitely do the trick.
